version: "3"

services:
  server:
    entrypoint: /bin/sh -c "yarn dev"
    volumes:
      - ./server/src:/app/src
    environment:
      STAGE: development
      PORT: 8081
    ports:
      - "8081:8081"

  client:
    entrypoint: "yarn start"
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8081
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public