version: "3"

services:
  server:
    build: ./server
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      STAGE: production
      PORT: 8081
      CORS: all
      FORCE_COLOR: 1

  client:
    build:
      context: ./client
      args:
        ENV: production
    ports:
      - "3000:3000"
    environment:
      ENV: production
      REACT_APP_API_URL: https://htfm.example.com/api

